# Generated by Django 4.0.5 on 2022-06-27 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('body', models.TextField()),
                ('username', models.CharField(blank=True, default='Anonymous', max_length=100, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField()),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subj', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('time_of', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=80, null=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Subject', models.CharField(choices=[('1', 'UFO/UAPs nature'), ('2', 'Origins of UFO/Aliens'), ('3', 'Where they come from'), ('4', 'Their intentions'), ('5', 'Other')], max_length=10)),
                ('Details', models.TextField()),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Visible', 'Visible'), ('Hidden', 'Hidden')], default='Visible', max_length=20)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
