# Generated by Django 4.0.5 on 2022-06-27 13:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='email',
            field=models.CharField(blank=True, default=datetime.datetime(2022, 6, 27, 13, 56, 25, 671841, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
